version: "3.8"
services:

    app:
        build:
            args:
                user: RS
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: repository-switcher
        container_name: repository-switcher-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - repository-switcher

    db:
        image: mysql:latest
        container_name: repository-switcher-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: repository-switcher-mysql
        volumes:
            - ./docker/mysql:/docker-entrypoint-initdb.d
        networks:
            - repository-switcher

    webserver:
        image: nginx:alpine
        container_name: repository-switcher-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - repository-switcher

networks:
    repository-switcher:
        driver: bridge
